name: Eric, the virtual world


# Tell Github to use the kramdown markdown interpreter
markdown: kramdown

# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /blog/:year/:month/:day/:title

exclude: [  "ReadMe.md", "License.md"]
